name: Build and Publish WebGoat
# This workflow builds the WebGoat project, scans artifacts with JFrog Xray, and publishes the Docker image to Docker Hub.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean install -Dmaven.compiler.release=17
      
    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: latest
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        
    - name: JFrog Xray Scan
      run: |
        # Configure JFrog CLI
        jf c add xray-server --url=${JF_URL} --access-token=${JF_ACCESS_TOKEN}
        
        # Scan the project artifacts without specifying a project
        jf scan target/*.jar --fail=false
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      
    # Build and push Docker image using Docker commands directly
    - name: Build Docker image
      run: |
        # Build the Docker image
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webgoat:latest .
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/webgoat:latest ${{ secrets.DOCKERHUB_USERNAME }}/webgoat:sha-${{ github.sha }}
        
        # List built images
        echo "Built Docker images:"
        docker images | grep webgoat
    
    # Push to Docker Hub if on main branch
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        # Push the Docker image to Docker Hub
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/webgoat:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/webgoat:sha-${{ github.sha }}
        
    # Scan the Docker image after building
    - name: Scan Docker image with JFrog Xray
      run: |
        # Get the full Docker image name with tag
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/webgoat:latest"
        echo "Scanning Docker image: ${IMAGE_NAME}"
        
        # Scan the Docker image
        jf docker scan ${IMAGE_NAME} --fail=false
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
