name: Build and Publish WebGoat
# This workflow builds the WebGoat project, scans artifacts with JFrog Xray, and publishes the Docker image to Docker Hub.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean install -Dmaven.compiler.release=17
      
    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: latest
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        
    - name: JFrog Xray Scan
      run: |
        # Configure JFrog CLI
        jf c add xray-server --url=${JF_URL} --access-token=${JF_ACCESS_TOKEN}
        
        # Scan the project artifacts without specifying a project
        jf scan target/*.jar --fail=false
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/webgoat
        tags: |
          type=ref,event=branch
          type=sha,format=short
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          
    # For debugging purposes, let's see what tags are generated
    - name: Debug Docker tags
      run: |
        echo "Generated tags: ${{ steps.meta.outputs.tags }}"
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      id: docker_build
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        # Load the image locally for testing if not pushing
        load: ${{ github.ref != 'refs/heads/main' }}
        
    # Debug step to list available Docker images
    - name: List Docker images
      run: docker images
        
    # Only run Docker scan on main branch and use specific image tag
    - name: Scan Docker image with JFrog Xray (Main branch only)
      if: github.ref == 'refs/heads/main'
      run: |
        # Get the full Docker image name with tag
        DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
        IMAGE_NAME="${DOCKER_USERNAME}/webgoat:latest"
        echo "Scanning Docker image: ${IMAGE_NAME}"
        
        # Pull the image to make sure it's available locally
        docker pull ${IMAGE_NAME}
        
        # Scan the Docker image
        jf docker scan ${IMAGE_NAME} --fail=false
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
