name: Build and Publish WebGoat
# This workflow builds the WebGoat project, scans artifacts with JFrog Xray, and publishes the Docker image to Docker Hub.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean install -Dmaven.compiler.release=17
      
    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: latest
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    
    # Generate SBOM for Maven artifacts
    - name: Generate SBOM for Maven project
      run: |
        # Install the CycloneDX Maven plugin if not already in pom.xml
        mvn org.cyclonedx:cyclonedx-maven-plugin:2.7.9:makeAggregateBom -DoutputFormat=json -DoutputName=bom
        
        # Move the SBOM to a more accessible location
        mkdir -p sbom
        mv target/bom.json sbom/maven-bom.json
        
        # Print SBOM info
        echo "Generated Maven SBOM at sbom/maven-bom.json"
        
    - name: JFrog Xray Scan with SBOM
      run: |
        # Configure JFrog CLI
        jf c add xray-server --url=${JF_URL} --access-token=${JF_ACCESS_TOKEN}
        
        # Scan the project artifacts
        jf scan target/*.jar --fail=false
        
        # Scan the SBOM
        jf scan sbom/maven-bom.json --format cyclonedx --fail=false
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      
    # Build and push Docker image using Docker commands directly
    - name: Build Docker image
      run: |
        # Build the Docker image
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webgoat:latest .
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/webgoat:latest ${{ secrets.DOCKERHUB_USERNAME }}/webgoat:sha-${{ github.sha }}
        
        # List built images
        echo "Built Docker images:"
        docker images | grep webgoat
    
    # Generate SBOM for Docker image
    - name: Generate SBOM for Docker image
      run: |
        # Install Syft (SBOM generator for containers)
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        
        # Generate SBOM in CycloneDX format
        syft ${{ secrets.DOCKERHUB_USERNAME }}/webgoat:latest -o cyclonedx-json=sbom/docker-bom.json
        
        # Print SBOM info
        echo "Generated Docker SBOM at sbom/docker-bom.json"
    
    # Push to Docker Hub if on main branch
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        # Push the Docker image to Docker Hub
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/webgoat:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/webgoat:sha-${{ github.sha }}
        
    # Scan the Docker image and its SBOM after building
    - name: Scan Docker image with JFrog Xray
      run: |
        # Get the full Docker image name with tag
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/webgoat:latest"
        echo "Scanning Docker image: ${IMAGE_NAME}"
        
        # Scan the Docker image
        jf docker scan ${IMAGE_NAME} --fail=false
        
        # Scan the Docker SBOM
        jf scan sbom/docker-bom.json --format cyclonedx --fail=false
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        
    # Upload SBOMs as artifacts
    - name: Upload SBOMs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sbom-files
        path: sbom/
        retention-days: 5
