name: Build and Publish WebGoat
# This workflow builds the WebGoat project, scans it with JFrog Xray, and publishes the Docker image to Docker Hub.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Removed release trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean install -Dmaven.compiler.release=17
      
    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: latest
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        
    - name: JFrog Xray Scan
      run: |
        # Configure JFrog CLI
        jf c add xray-server --url=${JF_URL} --access-token=${JF_ACCESS_TOKEN}
        
        # Scan the project artifacts without specifying a project
        jf scan target/*.jar --fail=false
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/webgoat
        tags: |
          type=ref,event=branch
          type=sha,format=short
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Scan Docker image with JFrog Xray
      if: github.ref == 'refs/heads/main'
      run: |
        # Scan the Docker image that was just pushed
        IMAGE_NAME=$(echo ${{ steps.meta.outputs.tags }} | cut -d' ' -f1)
        jf docker scan ${IMAGE_NAME} --fail=false
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
